import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../app/home/page.css"
import  CountryTrack  from "@/context/countryTrack";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Bihar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CountryTrack>
        {children}
        </CountryTrack>
       </body>
    </html>
  );
}
